#!/bin/bash

# trunk build --config extensions/chrome/Chrome.toml
cargo fmt --all

rm -rf ./dist-chrome
mkdir ./dist-chrome
mkdir ./dist-chrome/icons

cp -r ./core/resources/icons ./dist-chrome/
cp ./core/resources/images/kaspa-ng.svg ./dist-chrome/

cp ./extensions/chrome/style.css ./dist-chrome/
cp ./extensions/chrome/manifest.json ./dist-chrome/
cp ./extensions/chrome/popup.html ./dist-chrome/
cp ./extensions/chrome/popup.js ./dist-chrome/
cp ./extensions/chrome/background.js ./dist-chrome/
cp ./extensions/chrome/content-script.js ./dist-chrome/
cp ./extensions/chrome/api.js ./dist-chrome/

wasm-pack build $@ --target web --out-name kaspa-ng --out-dir ../../dist-chrome ./extensions/chrome/ --features browser-extension
