#!/usr/bin/env bash
cargo fmt --all
# cargo test --workspace --all-targets --all-features
# cargo test --workspace --doc
# cargo clippy --workspace --all-targets --all-features --  -D warnings -W clippy::all
# cargo clippy --workspace --all-targets --  -D warnings -W clippy::all
# cargo clippy --workspace --all-targets -- -W clippy::all
cargo clippy --workspace 
cargo clippy --workspace --target=wasm32-unknown-unknown
