#!/usr/bin/env bash
cargo fmt --all
# This scripts runs various CI-like checks in a convenient way.
# set -eux

# cargo check --workspace --all-targets
# cargo check --workspace --all-features --lib --target wasm32-unknown-unknown
# cargo fmt --all -- --check
# cargo test --workspace --all-targets --all-features
# cargo test --workspace --doc
# cargo clippy --workspace --all-targets --all-features --  -D warnings -W clippy::all
cargo clippy --workspace --all-targets --  -D warnings -W clippy::all
# trunk build
